FROM ubuntu:22.04
MAINTAINER "tom <dev.tedhan@gmail.com>"
LABEL "purpose"="webserver practice"
RUN apt-get update && apt-get install apache2 -y
WORKDIR /var/www/html
ADD index.html .
EXPOSE 80
CMD apachectl -D FOREGROUND

