FROM ubuntu:22.04
LABEL maintainer="tom <dev.tedhan@gmail.com>"
LABEL "purpose"="webserver practice"
RUN apt-get update && apt-get -y install apache2 \
                                         vim \
                                         curl \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /etc/apt/sources.list.d/*

ADD webapp.tar.gz /var/www/html
WORKDIR /var/www/html
EXPOSE 80
CMD /usr/sbin/apache2ctl -D FOREGROUND
