FROM alpine
MAINTAINER "tom <dev.tedhan@gmail.com>"
LABEL "purpose"="webserver practice"
RUN apk update && apk add apache2
WORKDIR /var/www/html
ADD index.html .
EXPOSE 80
CMD ["/usr/sbin/httpd","-D","FOREGROUND"]
